version: '3.8'

services:
  # React Frontend Service
  frontend:
    image: shipr-frontend:latest
    build:
      context: ./shipr-frontend
    ports:
      - "8081:80"
    depends_on:
      - shipr-inventory
      - shipr-payment

  # Shipr Inventory Python API Service
  shipr-inventory:
    image: shipr-inventory:latest
    build:
      context: ./shipr-inventory
    ports:
      - "8001:8000"
    depends_on:
      - redis

  # Shipr Payment Python API Service
  shipr-payment:
    image: shipr-payment:latest
    build:
      context: ./shipr-payment
    ports:
      - "8002:8000"
    depends_on:
      - shipr-inventory
      - redis

  # Redis for Shipr Inventory
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
