frontend:
  name: frontend
  repository: osamaazm/frontend
  tag: v1
  replicas: 1
  containerPort: 80
  type: NodePort
  service:
    port: 80
    targetport: 80
    nodePort: 30801
  labels:
    environment: production
    team: devops
    app: frontend

inventory:
  name: inventory
  repository: osamaazm/inventory
  tag: v1
  replicas: 1
  containerPort: 8000
  type: NodePort
  service:
    port: 8000
    targetport: 8000
    nodePort: 30802
  env:
    host-name: REDIS_HOST
    host-value: "redis"
    port-name: REDIS_PORT
    port-value: "6379"
  labels:
    environment: production
    team: devops
    app: inventory

payment:
  name: payment
  repository: osamaazm/payment
  tag: v1
  replicas: 1
  containerPort: 8000
  type: NodePort
  service:
    port: 8000
    targetport: 8000
    nodePort: 30803
  env:
    host-name: REDIS_HOST
    host-value: "redis"
    port-name: REDIS_PORT
    port-value: "6379"
    db-name: REDIS_DB
    db-value: "0"
    url-name: PRODUCT_SERVICE_URL
    url-value: "http://192.168.49.2:30802"
    fee-name: FEE_PERCENTAGE
    fee-value: "0.2"
  labels:
    environment: production
    team: devops
    app: payment

redis:
  name: redis
  repository: redis
  tag: alpine
  replicas: 1
  containerPort: 6379
  type: ClusterIP
  service:
    port: 6379
  volume:
    storage: 1Gi
    accessModes: ReadWriteOnce
    hostPath: /data/redis

ingress:
  name: shipr-ingress
  host: shipr.local
  frontend:
    path: /frontend
    pathType: Prefix
    service:
      name: shipr-frontend-service
      port: 80
  payment:
    path: /payment
    pathType: Prefix
    service:
      name: shipr-payment-service
      port: 8000
  inventory:
    path: /inventory
    pathType: Prefix
    service:
      name: shipr-inventory-service
      port: 8000
