frontend:
  name: frontend
  repository: osamaazm/frontend
  tag: v1
  replicas: 1
  containerPort: 80
  type: NodePort
  service:
    port: 80
    targetport: 80
    nodePort: 30801
  labels:
    environment: production
    team: devops
    app: frontend

inventory:
  name: inventory
  repository: osamaazm/inventory
  tag: v1
  replicas: 1
  containerPort: 8000
  type: NodePort
  configMapName: inventory-config
  service:
    port: 8000
    targetport: 8000
    nodePort: 30802
  env:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 0
  labels:
    environment: production
    team: devops
    app: inventory

payment:
  name: payment
  repository: osamaazm/payment
  tag: v1
  replicas: 1
  containerPort: 8000
  type: NodePort
  configMapName: payment-config
  service:
    port: 8000
    targetport: 8000
    nodePort: 30803
  env:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 0
    PRODUCT_SERVICE_URL: http://192.168.49.2:30802"
    FEE_PERCENTAGE: 0.2
  labels:
    environment: production
    team: devops
    app: payment

redis:
  name: redis
  repository: redis
  tag: alpine
  replicas: 1
  containerPort: 6379
  type: ClusterIP
  storageClassName: standard
  provisioner: k8s.io/minikube-hostpath
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  service:
    port: 6379
  volume:
    storage: 1Gi
    accessModes: ReadWriteOnce
    hostPath: /data/redis

ingress:
  enabled: true
  name: shipr-ingress
  host: shipr.local
  frontend:
    path: /frontend
    pathType: Prefix
    service:
      name: shipr-frontend-service
      port: 80
  payment:
    path: /payment
    pathType: Prefix
    service:
      name: shipr-payment-service
      port: 8000
  inventory:
    path: /inventory
    pathType: Prefix
    service:
      name: shipr-inventory-service
      port: 8000
