frontend:
  name: frontend
  repository: osamaazm/shipr-frontend
  tag: latest
  replicas: 1
  containerPort: 80
  type: NodePort
  use_probes: false
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
  service:
    port: 80
    targetport: 80
    nodePort: 30801
  labels:
    environment: production
    team: devops
    app: frontend
  resources:
    requests:
      set_requests: true
      memory: "128Mi"
      cpu: "500m"
    limits:
      set_limits: true
      memory: "256Mi"
      cpu: "1000m"

inventory:
  name: inventory
  repository: osamaazm/shipr-inventory
  tag: latest
  replicas: 1
  containerPort: 8000
  type: NodePort
  configMapName: inventory-config
  use_probes: false
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
  service:
    port: 8000
    targetport: 8000
    nodePort: 30802
  env:
    REDIS_HOST: redis
    REDIS_PORT: "6379"
    REDIS_DB: 0
  labels:
    environment: production
    team: devops
    app: inventory
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "256Mi"
      cpu: "1000m"


InventoryConsumer:
  name: inventory-consumer
  repository: osamaazm/shipr-inventory-consumer
  tag: latest
  replicas: 1
  containerPort: 8000
  type: NodePort
  configMapName: inventory-consumer-config
  use_probes: false
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
  service:
    port: 8000
    targetport: 8000
    nodePort: 30804
  labels:
    environment: production
    team: devops
    app: inventory-consumer
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "256Mi"
      cpu: "1000m"

payment:
  name: payment
  repository: osamaazm/shipr-payment
  tag: latest
  replicas: 1
  containerPort: 8000
  type: NodePort
  configMapName: payment-config
  use_probes: false
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
  service:
    port: 8000
    targetport: 8000
    nodePort: 30803
  env:
    REDIS_HOST: redis
    REDIS_PORT: "6379"
    REDIS_DB: 0
    PRODUCT_SERVICE_URL: http://192.168.49.2:8000
    FEE_PERCENTAGE: 0.2
  labels:
    environment: production
    team: devops
    app: payment
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "256Mi"
      cpu: "1000m"


PaymentConsumer:
  name: payment-consumer
  repository: osamaazm/shipr-payment-consumer
  tag: latest
  replicas: 1
  containerPort: 8000
  type: NodePort
  configMapName: payment-consumer-config
  use_probes: false
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
  service:
    port: 8000
    targetport: 8000
    nodePort: 30805
  labels:
    environment: production
    team: devops
    app: payment-consumer
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "256Mi"
      cpu: "1000m"

redis:
  name: redis
  repository: redis
  kind: StatefulSet
  tag: alpine
  replicas: 1
  containerPort: 6379
  type: ClusterIP
  storageClassName: standard
  provisioner: k8s.io/minikube-hostpath
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  skipStorageClass: true
  initialDelaySeconds: 10
  periodSeconds: 10
  restart_policy: Always
  pull_policy: IfNotPresent
  set_requests: false
  set_limits: false
  cpu_limits: "1000m"
  memory_limits: "256Mi"
  cpu_requests: "500m"
  memory_requests: "128Mi"
  storage:
    size: 5Gi
    accessMode: ReadWriteOnce
  service:
    port: 6379
  volume:
    storage: 1Gi
    accessModes:
      - ReadWriteOnce
      - ReadOnlyMany
    hostPath: /data/redis
  probes:
    liveness:
      enabled: true
    readiness:
      enabled: true
  labels:
    environment: production
    team: devops
    app: redis
  extraLabels:
    customLabel: "value"
  parameters:
    type: fast
    fsType: ext4
    encrypted: "false"
  mountOptions:
    option1: "rw"
    option2: "dirsync"
  selector:
    matchLabels:
      tier: backend

ingress:
  enabled: false
  name: shipr-ingress
  ingressClassName: nginx
  defaultBackend:
    name: default-backend
    port: 80
  tls:
    - hosts:
      - frontend.example.com
      secretName: frontend-tls
    - hosts:
      - payment.example.com
      secretName: payment-tls
    - hosts:
      - inventory.example.com
      secretName: inventory-tls
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  rules:
    - host: frontend.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend-service
            port: 80
    - host: payment.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: payment-service
            port: 8000
    - host: inventory.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: inventory-service
            port: 8001

