apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipr-frontend
  labels:
    app: shipr-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipr-frontend
  template:
    metadata:
      labels:
        app: shipr-frontend
    spec:
      containers:
      - name: shipr-frontend
        image: osamaazm/test-repo:shipr-frontend
        ports:
        - containerPort: 80
        resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "256Mi"
          cpu: "1000m"
