apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipr-inventory
  labels:
    app: shipr-inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipr-inventory
  template:
    metadata:
      labels:
        app: shipr-inventory
    spec:
      containers:
      - name: shipr-inventory
        image: osamaazm/inventory:v1
        ports:
        - containerPort: 8000
        env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_DB
            value: "0"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
