apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.redis.name }}
  labels:
    app: {{ .Values.redis.name }}
    {{- with .Values.redis.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.redis.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{  .Values.redis.name }}
    {{- if .Values.redis.extraLabels }}
    {{- range $key, $value := .Values.redis.extraLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      {{- if eq .Values.redis.type "NodePort" }}
      nodePort: {{ .Values.redis.service.nodePort | default "null" }}
      {{- end }}
  type: {{  .Values.redis.type }}