apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.redis.name }}
spec:
  selector:
    app: {{  .Values.redis.name }}
  ports:
    - protocol: TCP
      port: {{  .Values.redis.service.port }}
      targetPort: {{  .Values.redis.service.port }}
  type: {{  .Values.redis.type }}