apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.redis.storageClassName }}
provisioner: {{ .Values.redis.provisioner }}
reclaimPolicy: {{ .Values.redis.reclaimPolicy }}
volumeBindingMode: {{ .Values.redis.volumeBindingMode }}
