apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ Values.redis.name }}-pv
spec:
  capacity:
    storage: {{ Values.redis.volume.storage }}
  accessModes:
    - {{ Values.redis.volume.accessModes }}
  hostPath:
    path: {{ Values.redis.volume.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ Values.redis.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ Values.redis.storage }}
