apiVersion: apps/v1
kind: {{ .Values.redis.kind }}
metadata:
  name: {{ .Values.redis.name }}
  labels:
    app: {{ .Values.redis.name }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
      - name: {{ .Values.redis.name }}
        image: {{ .Values.redis.repository }}:{{ .Values.redis.tag }}
        ports:
        - containerPort: {{ .Values.redis.containerPort }}
        {{- if .Values.redis.probes.liveness.enabled }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.redis.containerPort }}
          initialDelaySeconds: {{ .Values.redis.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.periodSeconds }}
        {{- end }}
        {{- if .Values.redis.probes.readiness.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.redis.containerPort }}
          initialDelaySeconds: {{ .Values.redis.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.periodSeconds }}
        {{- end }}
        {{- if eq .Values.redis.kind "StatefulSet" }}
        volumeMounts:
        - mountPath: /data
          name: redis-storage
        {{- else }}
        volumeMounts:
        - mountPath: /data
          name: redis-storage
        {{- end }}
  {{- if eq .Values.redis.kind "StatefulSet" }}
  volumeClaimTemplates:
  - metadata:
      name: redis-storage
    spec:
      accessModes: 
        - {{ .Values.redis.storage.accessMode }}
      resources:
        requests:
          storage: {{ .Values.redis.storage.size }}
  {{- else }}
  volumes:
  - name: redis-storage
    persistentVolumeClaim:
      claimName: redis-pvc
  {{- end }}
