apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.InventoryConsumer.name }}
  labels: 
    app: {{ .Values.InventoryConsumer.name }}
spec:
  replicas: {{ .Values.InventoryConsumer.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.InventoryConsumer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.InventoryConsumer.name }}
    spec:
      containers:
      - name: {{ .Values.InventoryConsumer.name }}
        image: {{ .Values.InventoryConsumer.repository }}:{{ .Values.InventoryConsumer.tag }}
        ports:
        - containerPort: {{ .Values.InventoryConsumer.containerPort }}
        envFrom:
          - configMapRef:
              name: {{ .Values.inventory.configMapName }}
        {{- if .Values.InventoryConsumer.use_probes }}
        livenessProbe:
          httpGet:
            path: {{ .Values.InventoryConsumer.path }}
            port: {{ .Values.InventoryConsumer.containerPort }}
          initialDelaySeconds: {{ .Values.InventoryConsumer.initialDelaySeconds }}
          periodSeconds: {{ .Values.InventoryConsumer.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.InventoryConsumer.path }}
            port: {{ .Values.InventoryConsumer.containerPort }}
          initialDelaySeconds: {{ .Values.InventoryConsumer.initialDelaySeconds }}
          periodSeconds: {{ .Values.InventoryConsumer.periodSeconds }}
        startupProbe:
          httpGet:
            path: {{ .Values.InventoryConsumer.path }}
            port: {{ .Values.InventoryConsumer.containerPort }}
          initialDelaySeconds: {{ .Values.InventoryConsumer.initialDelaySeconds }}
          periodSeconds: {{ .Values.InventoryConsumer.periodSeconds }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.InventoryConsumer.resources.requests.memory }}
            cpu: {{ .Values.InventoryConsumer.resources.requests.cpu }}
          limits:
            memory: {{ .Values.InventoryConsumer.resources.limits.memory }}
            cpu: {{ .Values.InventoryConsumer.resources.limits.cpu }}
