apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.inventory.name }}
  labels:
    app: {{ .Values.inventory.name }}
spec:
  replicas: {{ .Values.inventory.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.inventory.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.inventory.name }}
    spec:
      containers:
      - name: {{ .Values.inventory.name }}
        image: {{ .Values.inventory.repository }}:{{ .Values.inventory.tag }}
        ports:
        - containerPort: {{ .Values.inventory.containerPort }}
        envFrom:
          - configMapRef:
              name: {{ .Values.inventory.configMapName }}
        {{- if .Values.inventory.use_probes }}
        livenessProbe:
          httpGet:
            path: {{ .Values.inventory.path }}
            port: {{ .Values.inventory.containerPort }}
          initialDelaySeconds: {{ .Values.inventory.initialDelaySeconds }}
          periodSeconds: {{ .Values.inventory.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.inventory.path }}
            port: {{ .Values.inventory.containerPort }}
          initialDelaySeconds: {{ .Values.inventory.initialDelaySeconds }}
          periodSeconds: {{ .Values.inventory.periodSeconds }}
        startupProbe:
          httpGet:
            path: {{ .Values.inventory.path }}
            port: {{ .Values.inventory.containerPort }}
          initialDelaySeconds: {{ .Values.inventory.initialDelaySeconds }}
          periodSeconds: {{ .Values.inventory.periodSeconds }}
        {{- end }}
        resources: 
          requests:
            memory: {{ .Values.inventory.resources.requests.memory }}
            cpu: {{ .Values.inventory.resources.requests.cpu }}
          limits:
            memory: {{ .Values.inventory.resources.limits.memory }}
            cpu: {{ .Values.inventory.resources.limits.cpu }}
